### ISSUE TITLE
errors with pip install clubs-gym

### ISSUE THREAD

**Issue by tkim135** [fschlatt/clubs_gym#2]
A couple other project teammates and I tried installing the repo through pip, and we ran into two problems:

1. It seems that `pip install clubs-gym` doesn't install `gym` accordingly, so it would be awesome if it could be clarified that `gym` is a required package.
2. When running the example script, line 1 (`from . import agent, configs, envs, poker`) of `__init__.py` bugs out saying `ImportError: cannot import name 'agent' from 'clubs'`. Digging into this deeper, this seems to be because `pip` does not download the folders inside `clubs` (`agent`, `envs`, `poker`, `render`). The only way we can run the code is if we clone the repo onto our local machines and run the `example.py` script in the repo.

Thank you for your help!

**Comment by fschlatt** [comment]
Thanks for the heads up. There seem to be multiple issues with the setup.py. I tried fixing them, but unfortunately cannot spend any more time on that for now. As you already pointed out, the solution for now would be to just clone the repo and install it locally with `pip install -e .` 

Sorry for any inconveniences. I hope to be able to fix everything over the weekend!

**Comment by fschlatt** [comment]
The package should now be installable using `pip install clubs-gym`
