### ISSUE TITLE
render method only works once

### ISSUE THREAD

**Issue by dhruvjoshi1998** [fschlatt/clubs_gym#3]
After rendering NoLimitHoldemTwoPlayer-v0 once, running render throws an InvalidRenderModeError from line 429 in clubs/poker/engine.py
Using python 3.8.5

![Screen Shot 2021-03-22 at 11 31 48 PM](https://user-images.githubusercontent.com/32560035/112088788-6cc39d80-8bb6-11eb-9453-e5c62c0ae994.png)

P.S. this is my first github issue, any advice on improving is appreciated

**Comment by fschlatt** [comment]
I updated the rendering (adding a sweet web server with front end render mode ;) ) in the base repository (https://github.com/fschlatt/clubs only the poker engine, no gym API) which should fix the issue. I hope to get around to updating this gym repo also soon.

Regarding your first issue: perfectly fine for this kind of small repository. Larger repositories often have a template to fill out, to give you a guide about what information is needed. Personally, I always like seeing attempts at solving the problem as well, not just posting the issue, but I know that many people don't have the time.

**Comment by fschlatt** [comment]
Should be fixed with the newest release
