### ISSUE TITLE
Only one hole_card is displayed in `env.reset()` (NoLimitHoldemTwoPlayer-v0)

### ISSUE THREAD

**Issue by JasonMendoza2008** [fschlatt/clubs_gym#4]
Considering the following code, I can't manage to access the hole_cards of both players (should have 4 hole_cards in total). I only get one - more precisely, `print(env.reset())` returns `{'action': 1, 'active': [True, True], 'button': 1, 'call': 1, 'community_cards': [], 'hole_cards': Card (1981034057104): 5♠, 'max_raise': 99, 'min_raise': 3, 'pot': 3, 'stacks': [98, 99], 'street_commits': [2, 1]}`. I would assume `observation['hole_cards']` should return more than just one card?

```py
import gym
import clubs_gym

env_str = "NoLimitHoldemTwoPlayer-v0"
num_players = 2
num_streets = 4
blinds = [1, 2]
antes = 0 
raise_sizes = ['inf', 'inf', 'inf', 'inf']
num_raises = 'inf' 
num_suits = 4
num_ranks = 13 
num_hole_cards = 2
mandatory_num_hole_cards = 0
num_community_cards = [0, 3, 1, 1]
start_stack = 100
n_cards_for_hand = 5 
order = ['sf', 'fk', 'fh', 'fl', 'st', 'tk', 'tp', 'pa', 'hc']

config_dict = {'num_players': num_players,
               'num_streets': num_streets,
               'blinds': blinds,
               'antes': antes,
               'raise_sizes': raise_sizes,
               'num_raises': num_raises,
               'num_suits': num_suits,
               'num_ranks': num_ranks,
               'num_hole_cards': num_hole_cards,
               'mandatory_num_hole_cards': mandatory_num_hole_cards,
               'num_community_cards': num_community_cards,
               'start_stack': start_stack,
               'num_cards_for_hand': n_cards_for_hand,
               'order': order}
clubs_gym.envs.register({env_str: config_dict})
env = gym.make(env_str)
print(env.reset())
```

I am using those versions of `clubs` and `clubs_gym`. I'm using `Python 3.9.10`. I'm on `Windows 11`.
```
clubs==0.1.4
clubs-gym==0.1.3
```

**Comment by fschlatt** [comment]
I changed the clubs API some time ago, but forgot to change the gym API accordingly. Will fix this as soon as possible

**Comment by JasonMendoza2008** [comment]
Thanks! I figured the static method `_parse_obs(obs)` was the problem. Is that it? It shouldn't replace `obs["hole_cards"]` by a given element of this list, should it? I'm not particularly familiar with `gym` so I might be wrong, but it felt like the problem was solved when the static method `_parse_obs(obs)` just returned `obs`. Looks like with this change I get the two cards of a given player. And I have to wait the next player's turn to get their cards.

**Comment by fschlatt** [comment]
Yes, that's correct. There are a couple of other typing additions I added into clubs which would have prevented the error, which I didn't transfer over to clubs_gym

**Comment by JasonMendoza2008** [comment]
Thank you for the responsiveness, much appreciated

**Comment by fschlatt** [comment]
Should be fixed ;)
